exp: 
  backbone: mit_b3

dataset:
  root_dir: /user33/objectdetection/train_all/
  name_list_dir: ./
  num_classes: 9
  crop_size: 320
  resize_range: [200,480]
  rescale_range: [0.5, 2.0]
  ignore_index: 255

train:
  split: train
  samples_per_gpu: 4
  max_iters: 20000
  eval_iters: 5000
  log_iters: 50

val:
  split: val

optimizer:
  type: AdamW
  learning_rate: 1e-4
  betas: [0.9, 0.999]
  weight_decay: 0.01

scheduler:
  warmup_iter: 1000
  warmup_ratio: 1e-4
  power: 1.0